# Generated by Django 5.2.8 on 2025-12-11 09:02

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.SlugField(unique=True)),
                ("description", models.CharField(blank=True, max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name="GitHubProfile",
            fields=[
                ("github_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="gateway.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("action", models.CharField(max_length=200)),
                (
                    "state",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("running", "RUNNING"),
                            ("succeeded", "SUCCEEDED"),
                            ("failed", "FAILED"),
                        ],
                        max_length=9,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="gateway.run",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ["pending", "running", "succeeded", "failed"])
                        ),
                        name="gateway_Job_state_State",
                    )
                ],
            },
        ),
    ]
