# Generated by Django 5.2.8 on 2026-03-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_token",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="login_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
