# Generated by Django 6.0.3 on 2026-07-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gateway", "0002_user_login_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="unrecognised",
            field=models.BooleanField(default=False),
        ),
    ]
